#あなたの身長は？(単位は㎝）
HEIGHT=165
print(f'あなたの身長は{HEIGHT}cmです。')
print('------')
#計算結果の表示メッセージ
kitchen_message='最適なキッチンの高さ(そのn)は'
#キッチンの高さの目安計算(その１)
#キッチンの高さ＝身長[cm]÷2+5cm
#キッチンの高さの目安計算(その２)
#キッチンの高さ＝肘高cm-10cm
#肘高はおよそ「身長[cm]-60cm」と言われています。
kitchen1=HEIGHT/2+5
message=kitchen_message.replace('そのn','その1')
print(f'{message}{kitchen1}cmです。')
print('------')
kitchen2=HEIGHT-60-10
message=kitchen_message.replace('そのn','その2')
print(f'{message}{kitchen2}です。')
print('------')